version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile-backend
    container_name: todolist-backend
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - ./todolist.db:/app/todolist.db

  frontend:
    build:
      context: .
      dockerfile: Dockerfile-frontend
    container_name: todolist-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: unless-stopped
